### ISSUE TITLE
EPIC: Capture User Interest

### ISSUE THREAD

**Issue by AllenDCooper** [emilybaum/thissociety#2]
## User Story
As a young adult, I want a tool to help me pursue my interests, so that I can better myself. 
## Acceptance Criteria 
 - [x] index.html includes form for capturing user interest
 - [x] index.html includes a submit button that when pushed, generates a series of steps for helping a user generate their interest.
- [x] index.html includes a link to search.html
